name: 'airbnb'
version: '1.0.0'
config-version: 2

profile: 'airbnb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
models:
  airbnb:
    data_lake:
      +enabled: true
      +materialized: table
      +schema: data_lake
    data_warhouse:
      +enabled: true
      +materialized: table
      +schema: data_warhouse
    data_analytics:
      +enabled: true
      +materialized: table 
      +schema: analytics_layer
